feat(dashboard): render plans in a table
litespace-org/litespace pull request #2
Opened 2024-10-11 21:50 UTC by moalidv

2024-10-13 13:03 UTC, neuodev requested changes
Great @moalidv! You code is clean and meet our coding standards. Please take a look at my minor comments. Thanks in advance!

2024-10-13 13:03 UTC, neuodev commented on packages/luna/src/components/Form/Controller.tsx
> +  name: N;
```
export function NumericInput<T extends FieldValues>({
  control,
  name,
  rules,
  ...props
}: {
  control: Control<T>;
  name: Path<T>;
```

2024-10-13 13:03 UTC, neuodev commented on packages/luna/src/locales/ar-eg.json
> +  "dashboard.plan.weeklyMinutes": "الدقائق في الأسبوع",
```suggestion
  "dashboard.plan.weeklyMinutes": "الدقائق الإسبوعية",
```

2024-10-13 13:03 UTC, neuodev commented on packages/luna/src/locales/ar-eg.json
> +  "dashboard.plan.forInvitesOnly": "يمكن دعوة أشخاص",
```suggestion
  "dashboard.plan.forInvitesOnly": "مخصصه لدعوة الاشخاص فقط",
```

2024-10-14 06:17 UTC, neuodev commented
![image](https://github.com/user-attachments/assets/f71dd939-15fb-4889-ad1a-aa4c557ae830)

Please truncate the table header text (check [this](https://tailwindcss.com/docs/text-overflow) and [this](https://css-tricks.com/snippets/css/truncate-string-with-ellipsis/)) and the full text should be shown in the a popover when hovering over a specific column header.

2024-10-14 06:19 UTC, neuodev commented on apps/dashboard/src/components/Plans/List.tsx
> +  if (!query.data) return null;
@moalidv please implement the error element.

2024-10-14 06:22 UTC, neuodev commented
![image](https://github.com/user-attachments/assets/0a86d1ca-80b7-459e-9bc6-881317a15f33)

This filed should be a `Duration` input.

2024-10-14 06:25 UTC, neuodev commented
![image](https://github.com/user-attachments/assets/f894b4d5-8d1a-4b39-bd33-7f569df2ecb1)

Let's try making our commitment more specific. *some* is a generic description.  *implement some changes* is quite unclear. 

Please update your commitment description to be more specific. Here how you can update you commitment message in `git`

- https://kodekloud.com/blog/change-commit-message-in-git/ 
- https://hackernoon.com/beginners-guide-to-interactive-rebasing-346a3f9c3a6d

2024-10-17 08:36 UTC, neuodev requested changes

2024-10-17 08:36 UTC, neuodev commented on apps/dashboard/src/components/Plans/List.tsx
> +        header: intl("dashboard.plans.alias.header"),
```suggestion
        header: intl("dashboard.plans.id"),
        cell: (info) => info.getValue(),
      }),
      columnHelper.accessor("alias", {
        header: intl("dashboard.plans.alias"),
```

2024-10-17 08:36 UTC, neuodev commented on apps/dashboard/src/components/Plans/List.tsx
> +        header: intl("dashboard.plans.createdAt.header"),
```suggestion
        header: intl("dashboard.plans.createdAt"),
```

2024-10-17 08:36 UTC, neuodev commented on apps/dashboard/src/components/Plans/List.tsx
> +        header: intl("dashboard.plans.updatedAt.header"),
```suggestion
        header: intl("dashboard.plans.updatedAt"),
```

2024-10-17 18:53 UTC, moalidv commented on apps/dashboard/src/components/Plans/List.tsx
> +        header: intl("dashboard.plans.alias.header"),
Done!!

2024-10-17 18:53 UTC, moalidv commented on apps/dashboard/src/components/Plans/List.tsx
> +        header: intl("dashboard.plans.createdAt.header"),
Done!!

2024-10-17 18:54 UTC, moalidv commented on apps/dashboard/src/components/Plans/List.tsx
> +        header: intl("dashboard.plans.updatedAt.header"),
Done!

2024-10-17 19:55 UTC, moalidv commented on apps/dashboard/src/components/Plans/List.tsx
> +  if (!query.data) return null;
> Please handle the error state as well. Similar to what we are doing [here](https://github.com/litespace-org/litespace/blob/b0dd38c003da73eea86f78677a03dd8cb0458943/apps/nova/src/pages/Lessons.tsx#L52)

![image](https://github.com/user-attachments/assets/73a22587-f9cd-473c-918c-75b93a6a4d0f)

2024-10-17 19:58 UTC, moalidv commented on apps/dashboard/package.json
> +    "@litespace/sol": "workspace:^"
Done!

2024-10-17 19:59 UTC, moalidv commented on apps/dashboard/src/App.tsx
> +import Plans from "./pages/Plans";
Done!

2024-10-17 20:00 UTC, moalidv commented on apps/dashboard/src/components/Plans/List.tsx
> +import PlanForm from "./PlanForm";
Done!

2024-10-17 20:00 UTC, moalidv commented on apps/dashboard/src/components/Plans/List.tsx
> +  }, []);
Done!

2024-10-17 20:01 UTC, moalidv commented on apps/dashboard/src/components/Plans/List.tsx
> +        header: "id",
Done!

2024-10-17 20:13 UTC, moalidv commented on apps/dashboard/src/components/Plans/PlanForm.tsx
> +        className="min-w-96 max-h-[32rem]  overflow-y-auto scrollbar-thin scrollbar-thumb-border-stronger scrollbar-track-surface-300"
Done!

2024-10-17 20:13 UTC, moalidv commented on apps/dashboard/src/components/Plans/PlanForm.tsx
> +              <Controller.NumericInput
Done!

2024-10-17 20:15 UTC, moalidv commented on packages/luna/src/locales/ar-eg.json
> +  "dashboard.plan.weeklyMinutes": "الدقائق في الأسبوع",
Done!

2024-10-17 21:40 UTC, neuodev approved these changes

2024-10-17 21:40 UTC, merged