feat(luna): added rate lesson dialog
litespace-org/litespace pull request #230
Opened 2024-12-18 12:52 UTC by mostafakamar2308

I chose to make the initial value of the rating 5 as this would influence students to give perfect scores for tutors.
We can control the initial value by usign `initialRating` prop

![image](https://github.com/user-attachments/assets/fb228734-17f6-4225-bc43-8cd24a127513)
![image](https://github.com/user-attachments/assets/e240f512-4639-465c-9b8c-aec510ef2175)
![image](https://github.com/user-attachments/assets/77df1a25-51a8-4a4e-a5b0-d919f080965e)

2024-12-18 12:56 UTC, neuodev commented
🚀 [Nova](https://nova-ohcc9s576-litespace-core.vercel.app) 
🚀 [Luna](https://luna-9fwtxf64k-litespace-core.vercel.app) 
🚀 [Nebula](https://nebula-3geqw7g5z-litespace-core.vercel.app) 
🚀 [Dashboard](https://dashboard-4h6b67jc0-litespace-core.vercel.app)

2024-12-18 13:25 UTC, neuodev commented
🚀 [Nova](https://nova-9mrnw2any-litespace-core.vercel.app) 
🚀 [Luna](https://luna-bvdd6yvpe-litespace-core.vercel.app) 
🚀 [Nebula](https://nebula-gn4trpkfk-litespace-core.vercel.app) 
🚀 [Dashboard](https://dashboard-aixql7yxi-litespace-core.vercel.app)

2024-12-19 09:28 UTC, neuodev requested changes

2024-12-19 09:28 UTC, neuodev commented on packages/luna/src/components/Lessons/RateLesson/RateLesson.tsx
> +   * whether you are rating session or the platform itself
```suggestion
   * Whether you are rating a session or the platform itself.
```

2024-12-19 09:28 UTC, neuodev commented on packages/luna/src/components/Lessons/RateLesson/RateLesson.tsx
> +    id: number;
No need to pass the ratee id to the `onRate` handler. The parent component is already aware of it. This is not the case for feedback and value. 

```suggestion
```

2024-12-19 09:28 UTC, neuodev commented on packages/luna/src/components/Lessons/RateLesson/RateLesson.tsx
> +  const onFeedbackchange = useCallback(
```suggestion
  const onFeedbackChange = useCallback(
```

2024-12-19 09:28 UTC, neuodev commented on packages/luna/src/components/Lessons/RateLesson/RateLesson.tsx
> +  const sendRating = useCallback(() => {
`send` will make the imperssion that you are sending it somewhere. This is not the case in your code. I think `setRating` is a better name.

2024-12-19 09:28 UTC, neuodev commented on packages/luna/src/components/Lessons/RateLesson/RateLesson.tsx
> +        </Typography>
Empty line please.

2024-12-19 09:28 UTC, neuodev commented on packages/luna/src/components/RatingStars/RatingStars.tsx
> +                console.log("setting rating", idx + 1);
Left over.

2024-12-19 09:28 UTC, neuodev commented on packages/luna/src/components/Textarea/Textarea.tsx
> +      />
We need to abaility to show error under that textarea. It should be the same as the input filed.

2024-12-19 09:28 UTC, neuodev commented on packages/luna/src/components/Lessons/RateLesson/RateLesson.tsx
> +  rateLoading: boolean;
Nice!

2024-12-19 09:28 UTC, neuodev commented on packages/luna/src/components/Lessons/RateLesson/RateLesson.tsx
> +  studentId: number;
You don't need the student id.

2024-12-19 11:42 UTC, neuodev commented
🚀 [Nova](https://nova-lmg0p5rng-litespace-core.vercel.app) 
🚀 [Luna](https://luna-ld9hn0mto-litespace-core.vercel.app) 
🚀 [Nebula](https://nebula-4x8v3kzge-litespace-core.vercel.app) 
🚀 [Dashboard](https://dashboard-dsexnizs8-litespace-core.vercel.app)

2024-12-19 17:30 UTC, neuodev requested changes

2024-12-20 13:49 UTC, mostafakamar2308 commented on packages/luna/src/components/Lessons/RateLesson/RateLesson.tsx
> +        />
I think it's 24px, isn't that right?

2024-12-20 13:58 UTC, neuodev commented
🚀 [Nova](https://nova-599tazeam-litespace-core.vercel.app) 
🚀 [Luna](https://luna-bhwf8a1ck-litespace-core.vercel.app) 
🚀 [Nebula](https://nebula-cl99sc18y-litespace-core.vercel.app) 
🚀 [Dashboard](https://dashboard-laf44x0wj-litespace-core.vercel.app)

2024-12-22 14:18 UTC, neuodev commented
🚀 [Nova](https://nova-68e84yasg-litespace-core.vercel.app) 
🚀 [Luna](https://luna-n1vczwdgf-litespace-core.vercel.app) 
🚀 [Nebula](https://nebula-i7edthaj0-litespace-core.vercel.app) 
🚀 [Dashboard](https://dashboard-i4k1lh6w6-litespace-core.vercel.app)

2024-12-22 16:29 UTC, neuodev requested changes

2024-12-22 16:29 UTC, neuodev commented on packages/luna/src/components/Textarea/Textarea.tsx
> +                {error}
If you checked the input component clearfly, you will notice that we render the helper text here and use the the error flag to give it an error color. Please check how this is implemented.

2024-12-22 16:29 UTC, neuodev commented on packages/luna/src/components/Lessons/RateLesson/RateLesson.tsx
> +        />
Yup, it is fixed! Thank you! 

جزاك الله خيرا يامصطفي.

2024-12-22 16:54 UTC, mostafakamar2308 commented on packages/luna/src/components/Lessons/RateLesson/RateLesson.tsx
> +        />
امين يارب واياكم ♥♥

2024-12-22 17:12 UTC, neuodev commented
🚀 [Nova](https://nova-jurq32kng-litespace-core.vercel.app) 
🚀 [Luna](https://luna-cqcl7mal7-litespace-core.vercel.app) 
🚀 [Nebula](https://nebula-8m0qljhc3-litespace-core.vercel.app) 
🚀 [Dashboard](https://dashboard-avy42vcqp-litespace-core.vercel.app)

2024-12-22 17:26 UTC, neuodev approved these changes

2024-12-22 17:26 UTC, merged