feat(sol): integrated humanize-duration library to format duration
litespace-org/litespace pull request #24
Opened 2024-10-24 11:49 UTC by mostafakamar2308

I also updated one line at `slot.test.ts` as it caused an error due to outdated types.

2024-10-24 12:09 UTC, neuodev commented
🚀 Nova: https://nova-6nzd3rno9-litespace-cores-projects.vercel.app
🚀 Luna: https://luna-nnrgkyuz7-litespace-cores-projects.vercel.app
🚀 Nebula: https://nebula-ijrz7e9lb-litespace-cores-projects.vercel.app

2024-10-30 07:43 UTC, neuodev commented
> I also updated one line at slot.test.ts as it caused an error due to outdated types.

Slots are deprecated. We replaced them with rules.

2024-10-30 07:46 UTC, neuodev requested changes
Please make sure that all tests are passing.

2024-10-30 07:46 UTC, neuodev commented on packages/sol/tests/duration.test.ts
> +  it("should format durations to EN", () => {
```suggestion
  it("should format durations in English", () => {
```

2024-10-30 07:46 UTC, neuodev commented on packages/sol/tests/duration.test.ts
> +  it("should format durations to AR", () => {
```suggestion
  it("should format durations in Arabic", () => {
```

2024-10-30 07:46 UTC, neuodev commented on packages/sol/tests/duration.test.ts
> +    expect(Duration.from("").format("en")).to.be.eq("0 minutes");
Incase of `0` minutes. I think we should return empty string.

2024-10-30 07:46 UTC, neuodev commented on packages/luna/src/hooks/duration.ts
Grate work. Please also remove these labels from `ar-EG.json`

2024-10-30 13:24 UTC, mostafakamar2308 commented on packages/luna/src/hooks/duration.ts
what labels?

2024-10-30 16:36 UTC, neuodev commented
🚀 Nova: https://nova-kvva1nm08-litespace-cores-projects.vercel.app
🚀 Luna: https://luna-lrkx110bg-litespace-cores-projects.vercel.app
🚀 Nebula: https://nebula-daqdt1m4i-litespace-cores-projects.vercel.app

2024-10-30 18:18 UTC, neuodev commented on packages/luna/src/hooks/duration.ts
https://github.com/litespace-org/litespace/pull/24#discussion_r1823169665

2024-10-31 11:31 UTC, neuodev commented
🚀 Nova: https://nova-i0yn3jje0-litespace-cores-projects.vercel.app
🚀 Luna: https://luna-3v26y5enp-litespace-cores-projects.vercel.app
🚀 Nebula: https://nebula-36fa3kzso-litespace-cores-projects.vercel.app

2024-10-31 15:08 UTC, neuodev commented on pnpm-lock.yaml
Why do we have a changes in the `pnpm-lock.yaml` file? Make sure not to introduce unrelated changes in your PRs.

2024-11-03 12:22 UTC, neuodev commented
🚀 Nova: https://nova-ka4a5ozhj-litespace-cores-projects.vercel.app
🚀 Luna: https://luna-bfzwd14l1-litespace-cores-projects.vercel.app
🚀 Nebula: https://nebula-6bgxj1q9s-litespace-cores-projects.vercel.app

2024-11-03 18:13 UTC, neuodev approved these changes

2024-11-03 18:13 UTC, merged