added: coverage unit tests for redis cache component.
litespace-org/litespace pull request #242
Opened 2024-12-23 14:34 UTC by mmoehabb

2024-12-23 15:59 UTC, neuodev requested changes

2024-12-23 15:59 UTC, neuodev commented on packages/models/tests/cache/call.test.ts
> +const cache = new Cache(process.env.REDIS_URL || "");
No to create this cache object for each test file, we can move it into a fixture.

2024-12-23 16:56 UTC, mmoehabb commented
The pipeline before [this change](https://github.com/litespace-org/litespace/pull/242/commits/9ce9716f49058ad08dffb0994308db2f6fe9a887) kept raising an error due to primary key violation. Local testing, on the other hand, raises no errors at all. I've worked around this tedious error by using a hard-coded values in the corresponding unit test; as shown in [the commit](https://github.com/litespace-org/litespace/pull/242/commits/9ce9716f49058ad08dffb0994308db2f6fe9a887).

2024-12-24 05:15 UTC, neuodev commented
> The pipeline before [this change](https://github.com/litespace-org/litespace/pull/242/commits/9ce9716f49058ad08dffb0994308db2f6fe9a887) kept raising an error due to primary key violation. Local testing, on the other hand, raises no errors at all. I've worked around this tedious error by using a hard-coded values in the corresponding unit test; as shown in [the commit](https://github.com/litespace-org/litespace/pull/242/commits/9ce9716f49058ad08dffb0994308db2f6fe9a887).

Sounds good 👌

2024-12-24 05:15 UTC, neuodev approved these changes

2024-12-24 05:16 UTC, merged