feat(nova): implemented rating tutor functionality
litespace-org/litespace pull request #249
Opened 2024-12-25 17:06 UTC by mostafakamar2308

2024-12-26 12:21 UTC, neuodev commented
🚀 [Nova](https://nova-p5nm9gla1-litespace-core.vercel.app) 
🚀 [Luna](https://luna-nm2c1ajgd-litespace-core.vercel.app) 
🚀 [Nebula](https://nebula-heszdg8zx-litespace-core.vercel.app) 
🚀 [Dashboard](https://dashboard-7udqp4xmf-litespace-core.vercel.app)

2024-12-26 17:08 UTC, neuodev commented
🚀 [Nova](https://nova-istuzint7-litespace-core.vercel.app) 
🚀 [Luna](https://luna-pyuena9d6-litespace-core.vercel.app) 
🚀 [Nebula](https://nebula-mxuyulnvv-litespace-core.vercel.app) 
🚀 [Dashboard](https://dashboard-hniombxdy-litespace-core.vercel.app)

2024-12-26 17:09 UTC, neuodev commented
🚀 [Nova](https://nova-istuzint7-litespace-core.vercel.app) 
🚀 [Luna](https://luna-85ufibck4-litespace-core.vercel.app) 
🚀 [Nebula](https://nebula-n9j2xo258-litespace-core.vercel.app) 
🚀 [Dashboard](https://dashboard-f0gsakjb8-litespace-core.vercel.app)

2024-12-26 18:14 UTC, neuodev requested changes
Great work! I left minor comments. Please take a look. 


### UI/UX

The actions menu button on the card (the 3 dots) is not that usable, You need to be quite accurate when you click it. Let's increase the whitespace arount it such that even if the user didn't click it directly it should still open the actions menu. NOTE: this should note affect the design.

2024-12-26 18:14 UTC, neuodev commented on apps/nova/src/components/TutorProfile/Ratings.tsx
> +    });
No need to show a toast message. Student can see the result of his action already.

2024-12-26 18:14 UTC, neuodev commented on apps/nova/src/components/TutorProfile/Ratings.tsx
> +    });
Same here.

2024-12-26 18:14 UTC, neuodev commented on packages/luna/src/components/TutorFeedback/RatingDialog.tsx
> +            onSubmit({ value: newRating, feedback: newFeedback || "" })
Incase no feedback, it should be null. 


```suggestion
            onSubmit({ value: newRating, feedback: newFeedback || null })
```

2024-12-26 18:14 UTC, neuodev commented on packages/luna/src/components/TutorFeedback/TutorRatingCard.tsx
> +                "tw-bg-brand-500 tw-rounded-full tw-absolute tw-flex tw-justify-center tw-items-center tw-z-quote",
Nice!

2024-12-26 18:14 UTC, neuodev commented on packages/luna/src/components/TutorFeedback/TutorRatingCard.tsx
> +            weight={"semibold"}
```suggestion
            weight="semibold"
```

2024-12-26 18:14 UTC, neuodev commented on apps/nova/src/components/TutorProfile/RateTutor.tsx
> +    });
No need to show a success toast.

2024-12-29 12:07 UTC, neuodev commented
🚀 [Nova](https://nova-a6v08r4uq-litespace-core.vercel.app) 
🚀 [Luna](https://luna-1co9llu0z-litespace-core.vercel.app) 
🚀 [Nebula](https://nebula-l5ux7jbmr-litespace-core.vercel.app) 
🚀 [Dashboard](https://dashboard-4qo0juo77-litespace-core.vercel.app)

2024-12-29 16:38 UTC, neuodev commented
🚀 [Nova](https://nova-ltxq2daoj-litespace-core.vercel.app) 
🚀 [Luna](https://luna-2rhewwt43-litespace-core.vercel.app) 
🚀 [Nebula](https://nebula-ao5sw5onb-litespace-core.vercel.app) 
🚀 [Dashboard](https://dashboard-eqx2rhts5-litespace-core.vercel.app)

2024-12-30 01:22 UTC, mmoehabb commented on packages/luna/src/components/TutorFeedback/RatingDialog.tsx
> +            (newFeedback === feedback && newRating === rating) || loading
Just a simple note: consider using the short simple expression first in the (or) condition.

2024-12-30 01:26 UTC, mmoehabb reviewed
I've only left a simple humble note. What an incredible work @mostafakamar2308. Kudos to you.

2024-12-30 01:28 UTC, mmoehabb approved these changes

2024-12-30 16:34 UTC, neuodev approved these changes

2024-12-30 16:34 UTC, neuodev commented on packages/luna/src/components/TutorFeedback/RatingDialog.tsx
> + * This dialog will be used for both editing Ratings and creating new rating
```suggestion
 * This dialog will be used for both editing ratings and creating new rating
```

2024-12-30 16:34 UTC, neuodev commented
@mostafakamar2308 please rebase, address the minor comment and merge you pull request. Thanks!

2024-12-30 17:35 UTC, neuodev commented
🚀 [Nova](https://nova-hr7w9abuh-litespace-core.vercel.app) 
🚀 [Luna](https://luna-qq84rksio-litespace-core.vercel.app) 
🚀 [Nebula](https://nebula-5rzz0x0eo-litespace-core.vercel.app) 
🚀 [Dashboard](https://dashboard-nnp7e2ale-litespace-core.vercel.app)

2024-12-30 17:57 UTC, merged