added(server): find personalized tutor stats endpoint.
litespace-org/litespace pull request #258
Opened 2024-12-29 15:26 UTC by mmoehabb

2024-12-29 15:31 UTC, neuodev commented
🚀 [Nova](https://nova-f36gogx1m-litespace-core.vercel.app) 
🚀 [Luna](https://luna-qzp26brkt-litespace-core.vercel.app) 
🚀 [Nebula](https://nebula-kksd5414n-litespace-core.vercel.app) 
🚀 [Dashboard](https://dashboard-8vhjn8f6i-litespace-core.vercel.app)

2024-12-29 16:18 UTC, mostafakamar2308 commented on services/server/src/handlers/user.ts
> +  ]);
executing them in parallel is a nice idea :)

2024-12-29 16:22 UTC, mostafakamar2308 approved these changes

2024-12-30 18:17 UTC, neuodev commented
@mmoehabb please rebase.

2024-12-30 18:18 UTC, neuodev requested changes

2024-12-30 19:43 UTC, neuodev commented
<!--
  0 failure: 
  1 warning:  No clickup task f...
  
  
  DangerID: danger-id-Danger;
-->


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>No clickup task found in this pull request</td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 79f1b2f98838d3d1016cae2281de6e82b6d60abf
</p>

2024-12-30 19:45 UTC, neuodev commented
🚀 [Nova](https://nova-fctz2g5bm-litespace-core.vercel.app) 
🚀 [Luna](https://luna-fti25omdc-litespace-core.vercel.app) 
🚀 [Nebula](https://nebula-hgrl9bus4-litespace-core.vercel.app) 
🚀 [Dashboard](https://dashboard-ow45pwwus-litespace-core.vercel.app)

2024-12-30 20:29 UTC, neuodev approved these changes

2024-12-30 20:29 UTC, merged