added(server): endpoint to retrieve all tutors that a user has not started a chat with yet.
litespace-org/litespace pull request #260
Opened 2024-12-30 00:24 UTC by mmoehabb

2024-12-30 00:28 UTC, neuodev commented
🚀 [Nova](https://nova-mnxafud0y-litespace-core.vercel.app) 
🚀 [Luna](https://luna-1aol44dh7-litespace-core.vercel.app) 
🚀 [Nebula](https://nebula-lj5pzud5h-litespace-core.vercel.app) 
🚀 [Dashboard](https://dashboard-7wu5cwq7t-litespace-core.vercel.app)

2024-12-30 19:29 UTC, neuodev commented
<!--
  0 failure: 
  1 warning:  No clickup task f...
  
  
  DangerID: danger-id-Danger;
-->


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>No clickup task found in this pull request</td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 9ac753efc99a90cb9d06e4ed328e5d2ca9e7e73e
</p>

2024-12-30 19:30 UTC, neuodev commented
🚀 [Nova](https://nova-fus8a75eh-litespace-core.vercel.app) 
🚀 [Luna](https://luna-blghpf4wo-litespace-core.vercel.app) 
🚀 [Nebula](https://nebula-j8vniaeqn-litespace-core.vercel.app) 
🚀 [Dashboard](https://dashboard-9s75gjpe9-litespace-core.vercel.app)

2024-12-30 20:28 UTC, neuodev commented
@mmoehabb please attache the clickup task url

2024-12-30 21:47 UTC, neuodev commented
🚀 [Nova](https://nova-3bynx2ugl-litespace-core.vercel.app) 
🚀 [Luna](https://luna-fkhki1lcs-litespace-core.vercel.app) 
🚀 [Nebula](https://nebula-1bpvjsz0r-litespace-core.vercel.app) 
🚀 [Dashboard](https://dashboard-83q4b3yrb-litespace-core.vercel.app)

2024-12-31 07:01 UTC, neuodev requested changes
Great work! I left minor comments. Please take a look. 

Let's reflect the naming across this PR from "new tutors" to "uncontacted tutors"

2024-12-31 12:27 UTC, neuodev commented
🚀 [Nova](https://nova-jsu5v0fzy-litespace-core.vercel.app) 
🚀 [Luna](https://luna-g56sdeirs-litespace-core.vercel.app) 
🚀 [Nebula](https://nebula-njy39kiss-litespace-core.vercel.app) 
🚀 [Dashboard](https://dashboard-pbtx6mo5j-litespace-core.vercel.app)

2024-12-31 12:29 UTC, mmoehabb commented on packages/atlas/src/user.ts
> +  async findNewTutors(
Exactly, "uncontacted" is what I was looking for :sweat_smile: ... thanks.

2025-01-01 11:08 UTC, neuodev approved these changes

2025-01-01 11:08 UTC, neuodev commented on packages/types/src/tutor.ts
> + * openned a chat room.
The description is outdated.

2025-01-01 11:48 UTC, neuodev commented
🚀 [Nova](https://nova-nk6jpj2j5-litespace-core.vercel.app) 
🚀 [Luna](https://luna-1hpos9s04-litespace-core.vercel.app) 
🚀 [Nebula](https://nebula-bg71xhfg8-litespace-core.vercel.app) 
🚀 [Dashboard](https://dashboard-2rlqjkl1z-litespace-core.vercel.app)

2025-01-01 12:07 UTC, merged