feat(luna): improved chat message and groups
litespace-org/litespace pull request #264
Opened 2024-12-30 15:08 UTC by mostafakamar2308

2024-12-30 15:12 UTC, neuodev commented
🚀 [Nova](https://nova-6d0phuu7r-litespace-core.vercel.app) 
🚀 [Luna](https://luna-2ny9eaj7x-litespace-core.vercel.app) 
🚀 [Nebula](https://nebula-jc9efhtfs-litespace-core.vercel.app) 
🚀 [Dashboard](https://dashboard-nkzow7dfl-litespace-core.vercel.app)

2024-12-30 16:21 UTC, neuodev commented
🚀 [Nova](https://nova-lxugnngt8-litespace-core.vercel.app) 
🚀 [Luna](https://luna-feghv0ktj-litespace-core.vercel.app) 
🚀 [Nebula](https://nebula-fcd8f8ffy-litespace-core.vercel.app) 
🚀 [Dashboard](https://dashboard-pqm43zibb-litespace-core.vercel.app)

2024-12-30 19:22 UTC, mmoehabb requested changes
Awesome work, I loved it. Especially the MessageCap :smiley:

2024-12-30 19:22 UTC, mmoehabb commented on packages/luna/src/components/Chat/ChatMessage/ChatMessage.stories.tsx
LGTM.

2024-12-30 19:22 UTC, mmoehabb commented on packages/luna/src/components/Chat/ChatMessage/ChatMessage.tsx
> +            className={cn("-tw-top-1 tw-absolute", {
Let's add the dark mode styles in the Cap just like in the message box itself.
We may need to define/extend `tw-fill-brand-400` in tailwind first.

2024-12-31 18:21 UTC, mostafakamar2308 commented on packages/assets/package.json
> +    "./Check4": "./dist/Check4.tsx",
Each is used in different unique scenarios

2025-01-01 11:41 UTC, neuodev commented
<!--
  0 failure: 
  1 warning:  No clickup task f...
  
  
  DangerID: danger-id-Danger;
-->


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>No clickup task found in this pull request</td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 0dbcabcad05d1d7d41a2305a029a7a58e6de5f5a
</p>

2025-01-01 12:36 UTC, neuodev commented
🚀 [Nova](https://nova-nk6jpj2j5-litespace-core.vercel.app) 
🚀 [Luna](https://luna-gtnmeelvb-litespace-core.vercel.app) 
🚀 [Nebula](https://nebula-bwks9xgj2-litespace-core.vercel.app) 
🚀 [Dashboard](https://dashboard-p66ob4xdk-litespace-core.vercel.app)

2025-01-01 21:07 UTC, mmoehabb requested changes

2025-01-01 21:09 UTC, mmoehabb commented on packages/assets/assets/check4.svg
Sorry, I meant left not right. 
Look, this is how it renders on my browser (on github).

![Screenshot from 2025-01-01 22-50-32](https://github.com/user-attachments/assets/e01a5ff4-ebe4-4be1-9a89-9a89f5660587)

Is it different from yours?

2025-01-02 01:09 UTC, mostafakamar2308 commented on packages/assets/assets/check4.svg
nope you are right, I will see where is the problem 
Very nice Observation <3

2025-01-02 01:20 UTC, mostafakamar2308 commented on packages/luna/src/components/Chat/ChatMessage/ChatMessage.tsx
> +            <div className="tw-w-[10px] tw-h-[10px]">
The problem arose only if I was zoomed out, I don't know why it happens,
but your solution is perfect, TY <3

2025-01-02 01:25 UTC, neuodev commented
🚀 [Nova](https://nova-n3g1bvhzs-litespace-core.vercel.app) 
🚀 [Luna](https://luna-363158lk4-litespace-core.vercel.app) 
🚀 [Nebula](https://nebula-2phlhzaov-litespace-core.vercel.app) 
🚀 [Dashboard](https://dashboard-brxgd09gy-litespace-core.vercel.app)

2025-01-05 12:11 UTC, neuodev requested changes

2025-01-05 12:11 UTC, neuodev commented on packages/assets/assets/check4.svg
There is something wrong with this icon.

2025-01-05 12:11 UTC, neuodev commented on packages/assets/assets/double-check.svg
This one as well.

2025-01-05 12:11 UTC, neuodev commented on packages/luna/src/components/Chat/ChatMessage/ChatMessage.tsx
> +            <AlertCircle className="tw-scale-[62.5%]" />
Why do we need to scale it? Why not just assign it width and height?

2025-01-05 12:13 UTC, neuodev commented
![image](https://github.com/user-attachments/assets/792c676a-1360-4198-9f61-d4af26ed83c9)

There is not pending state in the new message design. The message should has one of there states: `sent`, `reached`, or `seen`.

2025-01-05 16:09 UTC, mostafakamar2308 commented
@neuodev for the pending state, I discussed the design of it with zeyad and setteled on just giving it opacity-50

2025-01-05 16:25 UTC, neuodev commented
🚀 [Nova](https://nova-kiww8zweb-litespace-core.vercel.app) 
🚀 [Luna](https://luna-mgfha41p3-litespace-core.vercel.app) 
🚀 [Nebula](https://nebula-2q5padpab-litespace-core.vercel.app) 
🚀 [Dashboard](https://dashboard-1ulwhpwlj-litespace-core.vercel.app)

2025-01-06 14:47 UTC, neuodev commented
🚀 [Nova](https://nova-e5iueeuh3-litespace-core.vercel.app) 
🚀 [Luna](https://luna-bep4q4yo0-litespace-core.vercel.app) 
🚀 [Nebula](https://nebula-50rh7rbyz-litespace-core.vercel.app) 
🚀 [Dashboard](https://dashboard-pes7zi6xn-litespace-core.vercel.app)

2025-01-06 15:18 UTC, neuodev approved these changes

2025-01-06 15:55 UTC, neuodev commented
🚀 [Nova](https://nova-830c7wi62-litespace-core.vercel.app) 
🚀 [Luna](https://luna-kk8ndjv55-litespace-core.vercel.app) 
🚀 [Nebula](https://nebula-1mziweh7b-litespace-core.vercel.app) 
🚀 [Dashboard](https://dashboard-r07f2cnc8-litespace-core.vercel.app)

2025-01-06 15:57 UTC, merged