feat(nova): implemented loading/error in chat with scroll behavior
litespace-org/litespace pull request #266
Opened 2024-12-31 14:23 UTC by mostafakamar2308

Clickup task: https://app.clickup.com/t/86977xbap

2024-12-31 14:27 UTC, neuodev commented
🚀 [Nova](https://nova-j2ckjlfiy-litespace-core.vercel.app) 
🚀 [Luna](https://luna-jrns5d06v-litespace-core.vercel.app) 
🚀 [Nebula](https://nebula-rodfgrmkw-litespace-core.vercel.app) 
🚀 [Dashboard](https://dashboard-8kifdhyyi-litespace-core.vercel.app)

2024-12-31 14:56 UTC, neuodev commented
🚀 [Nova](https://nova-khi6yu4t0-litespace-core.vercel.app) 
🚀 [Luna](https://luna-5gur0hwik-litespace-core.vercel.app) 
🚀 [Nebula](https://nebula-872dugnlx-litespace-core.vercel.app) 
🚀 [Dashboard](https://dashboard-r1223gxtp-litespace-core.vercel.app)

2025-01-02 00:41 UTC, mmoehabb requested changes

2025-01-02 00:41 UTC, mmoehabb commented on apps/nova/src/pages/Chat.tsx
> +        <div className="h-full w-full flex items-center justify-center flex-col gap-8">
This div renders before the error message. Inspect the app in action... after the loading spinner this div appears for one seconds then disappears to show an error message.

I can propose a workaround here: we can add an animation in this div (for instance, fade-in) that will get fired after a 1s delay.

2025-01-02 00:41 UTC, mmoehabb commented on apps/nova/src/components/Chat/Messages.tsx
> +      style={{ height: "calc(100vh - 106px)" }}
I highly recommend storing this value `106px` somewhere. I am not sure where it should be but I am pretty sure storing and mutating it in one place would be better.

2025-01-02 00:41 UTC, mmoehabb commented on apps/nova/src/components/Chat/LoadingChat.tsx
Normally, I love repeating my self... It just makes your live easier. But here the repeating in `LoadingChat` and `LoadingChatError` tells us something. Maybe the `Typography` component and the corresponding parent `div` don't belong to these files!

Consider placing all the JSX here, but the `<Loader>...`, in the `Chat.tsx` component. And of course replace the gap with margin.

2025-01-02 00:41 UTC, mmoehabb commented on apps/nova/src/components/Chat/LoadingChatError.tsx
Same as the `LoadingChat.tsx`.

2025-01-02 00:41 UTC, mmoehabb commented on apps/nova/src/components/Chat/RoomsContainer.tsx
> +      style={{ height: "calc(100vh - 106px)" }}
In case you considered storing this value `106px`, don't forget using it here.

2025-01-02 00:41 UTC, mmoehabb commented on apps/nova/src/components/Chat/RoomsContainer.tsx
> +  update: {
I am frustrated by looking at this type :laughing:
We may use the types folder to store this type, or even a part of it (notice rooms.all and rooms.pinned are the same).

> I am not sure yet what we are or are not storing in the types dir... you can store it in the above of this file; the point is that we need to divide it in parts seeking for simple and readable version.

## One (brief) feasible solution
You may add this in the above of the file:
```TS
type TogglePinFunc = ...
type Keyword = ...
type RoomsAttr = ...
```

2025-01-12 13:35 UTC, mostafakamar2308 commented on apps/nova/src/pages/Chat.tsx
> +        <div className="h-full w-full flex items-center justify-center flex-col gap-8">
Nice observation, 
this bug happens mainly when we switch from one chat to the other, and that's because we are saying if there is other member data render the messages component other than that render the start new message.

so I solved it by making 2 if statements:
- if there is other member data render the messages component
- if there is no room selected render the start new message component.

PS: in this [PR](https://github.com/litespace-org/litespace/pull/286/files#diff-61b4d6faa6e109cd83f37d7f826f075b2dade8027a7216b738f6d10080fe3f34) I added a skeleton loader to prevent any layout shift

2025-01-12 13:48 UTC, mostafakamar2308 commented on apps/nova/src/components/Chat/RoomsContainer.tsx
> +  update: {
Great suggestion, I defined some types above as `Rooms` for the pinned and all rooms, and seperated update content to toggleMute and togglePin. and this made it simpler and easier on the eye 😃

2025-01-12 14:04 UTC, neuodev commented
🚀 [Nova](https://nova-jstlynr18-litespace-core.vercel.app) 
🚀 [Luna](https://luna-dzca4nybb-litespace-core.vercel.app) 
🚀 [Nebula](https://nebula-8wi90btsy-litespace-core.vercel.app) 
🚀 [Dashboard](https://dashboard-7yqo2ez7g-litespace-core.vercel.app)

2025-01-12 19:55 UTC, mmoehabb approved these changes

2025-01-12 19:55 UTC, mmoehabb commented on apps/nova/src/components/Chat/Messages.tsx
> +      // 106 is the height of the app header
I don't think this comment is necessary. The reader can easily follow to the definition of `HEADER_HEIGHT`.

2025-01-12 19:55 UTC, mmoehabb commented
@mostafakamar2308 
Please, rebase on the master.

2025-01-13 05:56 UTC, neuodev commented
🚀 [Nova](https://nova-1qruefuki-litespace-core.vercel.app) 
🚀 [Luna](https://luna-1a0789e4e-litespace-core.vercel.app) 
🚀 [Nebula](https://nebula-5v1ewks6g-litespace-core.vercel.app) 
🚀 [Dashboard](https://dashboard-8jawnyhwq-litespace-core.vercel.app)

2025-01-13 06:14 UTC, merged

2025-01-13 06:26 UTC, neuodev commented
![image](https://github.com/user-attachments/assets/64251782-949b-4cad-b492-ab14f319eb60)

There is a problem with the navbar.

2025-01-13 06:26 UTC, neuodev requested changes

2025-01-13 06:26 UTC, neuodev commented on apps/nova/src/components/Layout/Sidebar.tsx
> +      }}
No need to use css styles. you can do this with tailwind. Please define these values in tailwind config. `shadow-sidebar z-sidebar`

2025-01-13 06:26 UTC, neuodev commented on apps/nova/src/components/Layout/Navbar.tsx
> +      }}
Please use tailwind here as well.

2025-01-13 06:26 UTC, neuodev commented on apps/nova/src/constants/ui.ts
> +export const HEADER_HEIGHT = 106;
First of all, it is super nice that you made use of the `constants/` folder. 

My question is what do you mean by `HEADER`? Do you mean the navbar? Also in which unit it is? 

To make it clear which unit it is we can do one of the following: 

```ts
export const HEADER_HEIGHT = '106px'; 
export const HEADER_HEIGHT_IN_PIXELS = 106;
/**
 * Header height in pixels.
 */
export const HEADER_HEIGHT = 106;
```

2025-01-13 06:26 UTC, neuodev commented on apps/nova/src/components/Chat/RoomsContainer.tsx
> +            className=" text-natural-950 mb-6"
```suggestion
            className="text-natural-950 mb-6"
```