feat(nova): impl manage schedule dialog for tutors
litespace-org/litespace pull request #267
Opened 2024-12-31 17:15 UTC by moalidv

2025-01-02 00:26 UTC, neuodev commented
🚀 [Nova](https://nova-83otj8ksa-litespace-core.vercel.app) 
🚀 [Luna](https://luna-m1ep2qrfi-litespace-core.vercel.app) 
🚀 [Nebula](https://nebula-24i2ul5k8-litespace-core.vercel.app) 
🚀 [Dashboard](https://dashboard-5zh8075vy-litespace-core.vercel.app)

2025-01-07 11:05 UTC, neuodev commented
🚀 [Nova](https://nova-fhqld6iuo-litespace-core.vercel.app) 
🚀 [Luna](https://luna-aq4ceslxl-litespace-core.vercel.app) 
🚀 [Nebula](https://nebula-7mxjg1dtu-litespace-core.vercel.app) 
🚀 [Dashboard](https://dashboard-avi6wjah8-litespace-core.vercel.app)

2025-01-07 11:10 UTC, neuodev commented
🚀 [Nova](https://nova-tr6bdf1hz-litespace-core.vercel.app) 
🚀 [Luna](https://luna-nw5s0zsck-litespace-core.vercel.app) 
🚀 [Nebula](https://nebula-3dny8asmn-litespace-core.vercel.app) 
🚀 [Dashboard](https://dashboard-gy7twhpip-litespace-core.vercel.app)

2025-01-07 11:14 UTC, neuodev commented
🚀 [Nova](https://nova-bg1lo2szf-litespace-core.vercel.app) 
🚀 [Luna](https://luna-mp4mf8va5-litespace-core.vercel.app) 
🚀 [Nebula](https://nebula-71v7owf90-litespace-core.vercel.app) 
🚀 [Dashboard](https://dashboard-b6f16vlc8-litespace-core.vercel.app)

2025-01-07 11:17 UTC, neuodev commented
<!--
  0 failure: 
  1 warning:  No clickup task f...
  
  
  DangerID: danger-id-Danger;
-->


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>No clickup task found in this pull request</td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against f015c1decb482993513d854d8958c22ee41be48e
</p>

2025-01-07 11:36 UTC, neuodev commented
🚀 [Nova](https://nova-87gyr7iwi-litespace-core.vercel.app) 
🚀 [Luna](https://luna-8e54xkyr2-litespace-core.vercel.app) 
🚀 [Nebula](https://nebula-k2ru4y6lo-litespace-core.vercel.app) 
🚀 [Dashboard](https://dashboard-gfinjmxqu-litespace-core.vercel.app)

2025-01-07 20:03 UTC, mmoehabb commented on packages/luna/src/components/ManageSchedule/ManageSchedule.tsx
> +                          add={canAdd ? () => addSlot({ day: iso }) : undefined}
Let's always show the add button if it's the last row to match the prototype. We can do so by changing the false clause.
```TS
add={canAdd ? () => addSlot({ day: iso }) : (isLast ? () => {}: undefined)}
```

2025-01-07 20:04 UTC, mmoehabb commented on packages/luna/src/components/ManageSchedule/ManageSchedule.tsx
> +                      <SlotRow
We may add `add={() => {}}` here in order to show the add button as mentioned in the previous comment.
> Don't forget to margin it properly (we may disable the remove button by disappearing  it).

2025-01-07 20:16 UTC, mmoehabb commented on packages/luna/src/components/ManageSchedule/ManageSchedule.tsx
Overall this component is really impressive... great work. However, I think it needs refactoring; It's a little buggy and not that smooth. that's probably because of the repetitive cumbersome computation for the `days` variable in the line 170. 

One feasible solution that came to my mind is to segregate the `div` in line 302 (that contains SlotRows) from the rest of this component, we may call the segregated component "SlotRowsContainer", it shall handle the state of its seven slots itself. Therefore, relieving the burden of managing so many slot states from the parent (ManageSchedule), and distributing it on seven different components.

Last thing to remark, consider dividing this script into several ones; meanly, extract SlotRow into its own ts file.

2025-01-07 20:28 UTC, mmoehabb commented on packages/luna/src/components/ManageSchedule/ManageSchedule.tsx
> +function asOptions(start: Dayjs, end: Dayjs): SelectList<string> {
All is done, except excluding the selected options from the next SlotRow options. e.g. a user is assigning a new slot from 01:00 PM Saturday to 01:30 PM Saturday, when he/she tries to assign another slot in the same day from 01:00 PM and to 01:30 PM shall not be available.

I believe we can approach this by defining a new parameter here that will be used to exclude some options.
```TS
function asOptions(start: Dayjs, end: Dayjs, exclude: IAvailabilitySlot.Slot[]): SelectList<string> {
...
}
```

> You may use [subtractSlots function](https://github.com/litespace-org/litespace/blob/master/packages/sol/src/availabilitySlots.ts#L110) from `packages/sol`. It can be helpful.

2025-01-07 20:39 UTC, moalidv commented on packages/luna/src/components/Checkbox/Checkbox.tsx
the design of the schedule first contained checkbox 
so I used checkbox and when the check box label was only string so you could only add string and couldn't style it 
so if we make it available for react nodes, we can add typography and style it.

2025-01-07 20:42 UTC, moalidv commented on packages/luna/src/components/Loading/LoadingError.tsx
not undefined we put default value for it.
I can imagine if we frequantly use for example medium sized loading error we can assign the dafault size medium and not write it every time 
like button component, it is by default have variant, type and size

2025-01-07 21:38 UTC, neuodev commented
🚀 [Nova](https://nova-l2ro4zscu-litespace-core.vercel.app) 
🚀 [Luna](https://luna-j2r3e8lod-litespace-core.vercel.app) 
🚀 [Nebula](https://nebula-plir42oe9-litespace-core.vercel.app) 
🚀 [Dashboard](https://dashboard-hd7wxhh1h-litespace-core.vercel.app)

2025-01-07 22:23 UTC, neuodev commented on packages/luna/src/locales/ar-eg.json
> +  "labels.cancel": "إلغاء",
We are moving away from using "global...." and instead using "labels." directly. 

cc @moalidv @mmoehabb

2025-01-08 19:06 UTC, moalidv commented on packages/luna/src/components/ManageSchedule/ManageSchedule.tsx
> +                          add={canAdd ? () => addSlot({ day: iso }) : undefined}
@mmoehabb 
but what if the use add a new line before fill the empty slots

2025-01-08 19:26 UTC, moalidv commented on packages/luna/src/components/Select/Select.tsx
> +        {showDropdownIcon ? (
I used to write in that way  (condition && component)  but Ahmed told me to use 
condition ? component : null    pattern    
so for consistancy I started to write in this way.

2025-01-08 19:28 UTC, moalidv commented on packages/luna/src/components/Select/Select.tsx
> +        <Value
Ok, but for me to understand more this case 
what if the label is undefined so nothing will be rendered 
what is the diff bet putting the condition and not

2025-01-08 19:42 UTC, neuodev commented
🚀 [Nova](https://nova-ho828zrv0-litespace-core.vercel.app) 
🚀 [Luna](https://luna-ggefr556r-litespace-core.vercel.app) 
🚀 [Nebula](https://nebula-11mbzaxc7-litespace-core.vercel.app) 
🚀 [Dashboard](https://dashboard-6jn4l6lho-litespace-core.vercel.app)

2025-01-08 22:55 UTC, mmoehabb commented on packages/luna/src/components/ManageSchedule/ManageSchedule.tsx
> +            {intl("global.labels.cancel")}
Sorry for the burden... @neuodev has mentioned that we are moving away from using "global..." to using "labels". Revert this to the initial implementation "labels.cancel".

2025-01-08 22:55 UTC, mmoehabb commented on packages/luna/src/locales/ar-eg.json
> +  "global.placeholder.from": "من",
Sorry, let's go back to "placeholder.from". As @neuodev has clarified the new convention.

2025-01-08 22:55 UTC, mmoehabb commented on packages/luna/src/components/Select/Select.tsx
> +        <Value
Honestly, I have no idea :face_with_diagonal_mouth:
When I pondered about that. I have guessed that maybe using `label` as the text content (and/or children component) of the `Typography` component isn't "enough" or "legitimate", so to speak, for react to re-render the component whenever `label` changes. It could be a bad implementation of `Typography` or a bug in react. In either case, using `label` outside (but linked to) Typography will do the job.

2025-01-08 22:59 UTC, mmoehabb commented on packages/luna/src/components/Select/Select.tsx
> +        {showDropdownIcon ? (
It's just a matter of taste. Let's stick with the convention for consistency.

2025-01-08 23:04 UTC, mmoehabb commented on packages/luna/src/components/Loading/LoadingError.tsx
Aha got it, we added the question mark so the user doesn't have to pass a value and the default is enabled instead.

2025-01-08 23:19 UTC, mmoehabb commented on packages/luna/src/components/ManageSchedule/ManageSchedule.tsx
> +                          add={canAdd ? () => addSlot({ day: iso }) : undefined}
Hmm... good point. We need to share this with Zeyad. The current implementation doesn't fully match the prototype. If it's okay, from UI/UX perspective, then let's leave it as it is. If it's not (from my point of view, there is a lot of empty space in the left side of the component), I propose adding disable version of the add button, or easily using a dynamic (smooth) width length rather than static.

2025-01-09 02:54 UTC, mmoehabb requested changes
All looks good. However, the component still needs some enhancements. I have added my suggestion to enhance it's rendering a little; by invoking re-rendering only when the user adds (and not selecting) slots.

2025-01-09 02:54 UTC, mmoehabb commented on packages/luna/src/components/ManageSchedule/SlotRow.tsx
> +    return asOptions(startOfSelection, endOfSelection);
This should be 
```TS
return asOptions(startOfSelection.add(30, "minutes"), endOfSelection);
````
in order to exclude the selected time in `from` from the options in `to`.

2025-01-09 02:54 UTC, mmoehabb commented on packages/luna/src/components/ManageSchedule/SlotRow.tsx
> +            value={start}
Use here `startOfOptions` rather than `start`.

2025-01-09 02:54 UTC, mmoehabb commented on packages/luna/src/components/ManageSchedule/SlotRow.tsx
> +            value={end}
Use here `endOfOptions` rather than `end`.

2025-01-09 02:54 UTC, mmoehabb commented on packages/luna/src/components/ManageSchedule/SlotRow.tsx
> +          <button type="button" onClick={add}>
Replace this line with the following:
```TS
<button type="button" onClick={() => add(startOfOptions, endOfOptions)}>
```
> See my comments on `SlotRowContainer.tsx` first

2025-01-09 02:54 UTC, mmoehabb commented on packages/luna/src/components/ManageSchedule/SlotRow.tsx
> +  onFromChange?: (value: string) => void;
We can remove these two: `onFromChange` and `onToChange`.
> See comments on `SlotRowContainer.tsx` before this one.

2025-01-09 02:54 UTC, mmoehabb commented on packages/luna/src/components/ManageSchedule/SlotRowContainer.tsx
> +  const setSlotDate = useCallback(
Modify this function to set both dates rather than one at a time.
```TS
const setSlotDates = useCallback(
  (id: number, start: string, end: string) => {
    setSlots((prev) => {
      const cloned = structuredClone(prev);
      const foundSlot = cloned.find((slot) => slot.id === id);
      if (foundSlot) { 
        foundSlot.start = start; 
        foundSlot.end = end;
      }
      return cloned;
    });
  },
  [setSlots]
);
```

2025-01-09 02:54 UTC, mmoehabb commented on packages/luna/src/components/ManageSchedule/SlotRowContainer.tsx
> +            onFromChange={(value) => setSlotDate(slot.id, "start", value)}
We should remove those two: `onFromChange` and `onToChange`; rendering slot rows each time a user selects a time is cumbersome.

2025-01-09 02:54 UTC, mmoehabb commented on packages/luna/src/components/ManageSchedule/SlotRowContainer.tsx
> +            add={canAdd ? () => addSlot({ day: iso }) : undefined}
Change this to the following:
```TS
add={isLast ? (start, end) => {
  setSlotDates(slot.id, start, end)
  addSlot({ day: iso })
} : undefined}
```

2025-01-09 02:54 UTC, mmoehabb commented on packages/luna/src/components/ManageSchedule/SlotRowContainer.tsx
> +          onFromChange={(value: string) => addSlot({ day: iso, start: value })}
And finally, replace those two with the following:
```TS
add={(start, end) => {
  addSlot({ day: iso, start, end })
  addSlot({ day: iso })
}}
```

2025-01-09 23:19 UTC, neuodev commented
🚀 [Nova](https://nova-fmw1f6ct3-litespace-core.vercel.app) 
🚀 [Luna](https://luna-km62qnd76-litespace-core.vercel.app) 
🚀 [Nebula](https://nebula-22mbbeq13-litespace-core.vercel.app) 
🚀 [Dashboard](https://dashboard-a3qec4np9-litespace-core.vercel.app)

2025-01-12 13:59 UTC, mostafakamar2308 approved these changes

2025-01-13 14:02 UTC, neuodev commented
🚀 [Nova](https://nova-bkrf69x1q-litespace-core.vercel.app) 
🚀 [Luna](https://luna-mjplpsdon-litespace-core.vercel.app) 
🚀 [Nebula](https://nebula-m4bvpjin5-litespace-core.vercel.app) 
🚀 [Dashboard](https://dashboard-2jmlo8qmb-litespace-core.vercel.app)

2025-01-15 10:17 UTC, neuodev approved these changes

2025-01-15 10:21 UTC, neuodev commented
🚀 [Nova](https://nova-6lisvjasa-litespace-core.vercel.app) 
🚀 [Luna](https://luna-dklkrisrw-litespace-core.vercel.app) 
🚀 [Nebula](https://nebula-j944j7602-litespace-core.vercel.app) 
🚀 [Dashboard](https://dashboard-id7ex09io-litespace-core.vercel.app)

2025-01-15 11:32 UTC, merged