added(sol): availability slots required general logic
litespace-org/litespace pull request #268
Opened 2024-12-31 21:15 UTC by mmoehabb

2024-12-31 21:19 UTC, neuodev commented
🚀 [Nova](https://nova-80iyp56t6-litespace-core.vercel.app) 
🚀 [Luna](https://luna-7ze162hle-litespace-core.vercel.app) 
🚀 [Nebula](https://nebula-geyqkulnf-litespace-core.vercel.app) 
🚀 [Dashboard](https://dashboard-d6wfaxgg4-litespace-core.vercel.app)

2025-01-01 11:43 UTC, neuodev requested changes

2025-01-01 11:43 UTC, neuodev commented on packages/sol/src/availabilitySlots.ts
> +export function getSubslotsBatch(
Let's stick to `SubSlots` instead of `Subslots` for readability.  In the description we can write `sub-slot` instead of `subslot`. 

```suggestion
export function getSubSlotsBatch(
```

2025-01-01 11:43 UTC, neuodev commented on packages/sol/src/availabilitySlots.ts
> +  slots: IAvailabilitySlot.Slot[],
I believe it is better to move the params description to be above the param itself.  The same applies to all other params.

```suggestion
  /**
   * List of the slots to be divided
   */
  slots: IAvailabilitySlot.Slot[], 
```

2025-01-01 11:43 UTC, neuodev commented on packages/sol/src/availabilitySlots.ts
> +  return false;
This is not how you check if you the new slot will fit in the remaining space in the parent slot. 

Here is the steps to do this. 
1. Subtract the parent slots from all subslots. The result will be all free sub-slots. 
2. Check if the new slot (`bookInfo`) fit in one or more sub-slot. It if does fit, this mean you can book this new slot.

2025-01-01 11:43 UTC, neuodev commented on packages/sol/src/availabilitySlots.ts
> +  });
The function is hard to understand from the first look. Let's use lodash `orderBy` for convenience. It is used [here](https://github.com/litespace-org/litespace/blob/ddc09149172b24c29ab774f769854ede9c66860a/services/server/src/lib/tutor.
ts#L105).

2025-01-01 14:32 UTC, neuodev commented
🚀 [Nova](https://nova-exweke196-litespace-core.vercel.app) 
🚀 [Luna](https://luna-1qyjkaby4-litespace-core.vercel.app) 
🚀 [Nebula](https://nebula-kbaf6urij-litespace-core.vercel.app) 
🚀 [Dashboard](https://dashboard-d1aa9v5se-litespace-core.vercel.app)

2025-01-01 15:15 UTC, neuodev requested changes

2025-01-01 15:15 UTC, neuodev commented on packages/sol/src/availabilitySlots.ts
> +   */
The JS Docs should be above the types.

2025-01-01 15:15 UTC, neuodev commented on packages/sol/src/availabilitySlots.ts
> +     start: string;
```suggestion
    /**
    * The new slot start as iso-utc datetime.
    */
     start: string;
```

2025-01-01 15:15 UTC, neuodev commented on packages/sol/src/availabilitySlots.ts
> +     duration: number; // in minutes
```suggestion
    /**
    * The new slot duration in minutes.
    */
     duration: number;
```

2025-01-01 15:15 UTC, neuodev commented on packages/sol/src/availabilitySlots.ts
> +      ...Schedule.splitBy(slot, filtered).map(event => ({
`Schedule` belongs to the old logic (rules) and it will be removed once we move to slots. Please write a similar logic here using our new terminology.

2025-01-01 15:15 UTC, neuodev commented on packages/sol/src/availabilitySlots.ts
> +// the boundaries are included in the intersection.
JS Docs should be multi-line comment.

2025-01-01 15:15 UTC, neuodev commented on packages/sol/src/availabilitySlots.ts
> +): boolean {
We can improve the function signature by applying these changes.

```suggestion
export function isIntersecting<T extends {start: string, end: string}>(
  target: T, 
  slots: T[]
): boolean {
```

This way the function is generic and we are not limited by the `GeneralSlot` type. 

> [!NOTE]
> Don't forget to remove `GeneralSlot` in case we don't need it.

2025-01-01 15:15 UTC, neuodev commented on packages/sol/src/availabilitySlots.ts
> +}
We can use more sophisticated logic like [this one](https://github.com/litespace-org/litespace/blob/aebee0e646360ee861098e57b12dd029098fca1a/packages/sol/src/rule.ts#L216-L222).

Here is a stackoverflow question about who to solve the [overlap problem](https://stackoverflow.com/questions/3269434/whats-the-most-efficient-way-to-test-if-two-ranges-overlap). 

![image](https://github.com/user-attachments/assets/3f57d901-6c1d-4fa6-b556-541e062c655b)

2025-01-01 15:15 UTC, neuodev commented on packages/sol/src/availabilitySlots.ts
> +  b: IAvailabilitySlot.GeneralSlot
```suggestion
/**
 *  checks if slot `a` can be considered as a super slot (contains) for slot `b` or not.
 */
export function isSuperSlot(
  a: IAvailabilitySlot.Slot, // `SubSlot` can never be a parent to another subslot!  
  b: IAvailabilitySlot.SubSlot
```

2025-01-01 15:15 UTC, neuodev commented on packages/sol/src/availabilitySlots.ts
> +  return true;
* You can make the code more clean (give it a try)
* You also need to verify the `parentId`. `slot.id === subslot.parentId`.

2025-01-01 16:28 UTC, mmoehabb commented on packages/sol/src/availabilitySlots.ts
> +): boolean {
Using generic here is not quite feasible; if the first parameter type is `Slot` then the second has to be an array of `Slots`, and this is not the case in some use cases (wherein the second parameter is a list of `SubSlot`s). This has an easy workaround, but it'll unnecessarily make the code ugly. The code was initially like that: `T extends IAvailabilitySlot.Slot | IAvailbilitySlot.SubStot`, but then I considered cleaning this generic verbose ugliness!

2025-01-01 17:06 UTC, mmoehabb commented on packages/sol/src/availabilitySlots.ts
> +  b: IAvailabilitySlot.GeneralSlot
`isSuperSlot` doesn't look in the parent-child relation. It checks if some slot/subslot contains another. Just like in set theory; a set is a subset of itself, and a subset can be a superset of subsets.

It's being in handy (with this signature) in the `canBook` function.

2025-01-01 17:06 UTC, mmoehabb commented on packages/sol/src/availabilitySlots.ts
> +  return true;
For the second check, I propose a function to create slots and subslots. It can easily be misused or forged.

2025-01-01 17:07 UTC, mmoehabb commented on packages/sol/src/availabilitySlots.ts
> +}
The logic in the screenshot doesn't meet the requirement of our use cases. We shall exclude the boundaries; meaning if the end of _x_ is the same as the start of _y_, we still consider them NOT intersecting.

> I just noticed that I wrote in the comment "The boundaries are includes", that's a mistake, they are excluded from the intersection.

I'm not sure what do you mean by the word "sophisticated". But the code [https://github.com/litespace-org/litespace/blob/aebee0e646360ee861098e57b12dd029098fca1a/packages/sol/src/rule.ts#L216-L222](here) is just like my first attempt to solve the problem, before trying to make it more efficient (using `continue`).

I've revised my code again and enhanced it for the sake of readability. Give it another look.

2025-01-01 17:57 UTC, neuodev commented
🚀 [Nova](https://nova-3yyifu8ak-litespace-core.vercel.app) 
🚀 [Luna](https://luna-lxfky2tx4-litespace-core.vercel.app) 
🚀 [Nebula](https://nebula-ghffaikuw-litespace-core.vercel.app) 
🚀 [Dashboard](https://dashboard-bp3djlyoe-litespace-core.vercel.app)

2025-01-01 17:57 UTC, mmoehabb commented on packages/sol/src/availabilitySlots.ts
> +  return true;
Or we can remove the id. What is it needed for?... I mean If a subslot _b_ is inside a slot _a_ but has a parent id that doesn't match the id of _a_, how could that matter or make a difference in any sense?

2025-01-01 17:58 UTC, neuodev commented
🚀 [Nova](https://nova-3yyifu8ak-litespace-core.vercel.app) 
🚀 [Luna](https://luna-lxfky2tx4-litespace-core.vercel.app) 
🚀 [Nebula](https://nebula-pnvnzp73b-litespace-core.vercel.app) 
🚀 [Dashboard](https://dashboard-i8dtig6nb-litespace-core.vercel.app)

2025-01-01 18:48 UTC, neuodev commented on packages/sol/src/availabilitySlots.ts
> +  return true;
The `subslot` in this case might not belong to the parent slot or it is for another user.

2025-01-01 18:51 UTC, neuodev commented on packages/sol/src/availabilitySlots.ts
> +  console.log(res)
Left over.

2025-01-01 18:51 UTC, neuodev commented on packages/sol/src/availabilitySlots.ts
> +): boolean {
Aha, got it.

2025-01-01 19:51 UTC, mmoehabb commented on packages/sol/src/availabilitySlots.ts
> +  return true;
Aha got it. Each tutor has his own slots, that what I was missing.

2025-01-01 20:22 UTC, neuodev commented
🚀 [Nova](https://nova-hej53265g-litespace-core.vercel.app) 
🚀 [Luna](https://luna-1gzpxboey-litespace-core.vercel.app) 
🚀 [Nebula](https://nebula-hzhe2p3x2-litespace-core.vercel.app) 
🚀 [Dashboard](https://dashboard-al6t9vmce-litespace-core.vercel.app)

2025-01-02 13:54 UTC, neuodev commented on packages/sol/src/availabilitySlots.ts
> +}
Aha, got it. I will take a look one more time into the implementation.

2025-01-02 14:08 UTC, neuodev reviewed
Greate work! I left a minor comment. We can merge this branch once it is addressed.

2025-01-02 14:08 UTC, neuodev commented on packages/sol/src/availabilitySlots.ts
> +  return false;
* No need to re-assign variables.
* We can make the code more cleaner. 

```suggestion
  for (const slot of slots) {
    // target slots started after the current slot.
    const startedAfterCurrentSlot = 
      dayjs.utc(target.start).isAfter(slot.end) || 
      dayjs.utc(target.start).isSame(slot.end);

    // target slots eneded before the current slot.
    const endedBeforeCurrentSlot = 
      dayjs.utc(target.end).isBefore(slot.start) || 
      dayjs.utc(target.end).isSame(slot.start);

    if (startedAfterCurrentSlot || endedBeforeCurrentSlot) return true
  }

  return false;
```

2025-01-02 14:08 UTC, neuodev commented on packages/sol/src/availabilitySlots.ts
> +  let mainSubSlot: IAvailabilitySlot.SubSlot = {
```suggestion
  const mainSubSlot: IAvailabilitySlot.SubSlot = {
```

2025-01-02 14:13 UTC, neuodev commented
@mmoehabb please rebase.

2025-01-02 17:06 UTC, neuodev commented
🚀 [Nova](https://nova-k1ps2qc3d-litespace-core.vercel.app) 
🚀 [Luna](https://luna-o5cn1h8gq-litespace-core.vercel.app) 
🚀 [Nebula](https://nebula-ly980hgyr-litespace-core.vercel.app) 
🚀 [Dashboard](https://dashboard-glvg9d7e1-litespace-core.vercel.app)

2025-01-02 17:45 UTC, neuodev commented on packages/sol/src/availabilitySlots.ts
> +  return false;
Ah, I spotted the issue. The logic above is about "not intersecting". It should return `false` then.

2025-01-02 17:47 UTC, neuodev commented on packages/sol/src/availabilitySlots.ts
> +  return false;
```ts
    if (!startedAfterCurrentSlot && !endedBeforeCurrentSlot) return true
```

2025-01-02 17:49 UTC, neuodev approved these changes

2025-01-02 18:07 UTC, mmoehabb commented on packages/sol/src/availabilitySlots.ts
> +  return false;
Aha got it.

2025-01-02 18:10 UTC, neuodev commented
🚀 [Nova](https://nova-jeodg2aod-litespace-core.vercel.app) 
🚀 [Luna](https://luna-4lwc31v39-litespace-core.vercel.app) 
🚀 [Nebula](https://nebula-3j33k60nl-litespace-core.vercel.app) 
🚀 [Dashboard](https://dashboard-mz7dklduo-litespace-core.vercel.app)

2025-01-02 18:11 UTC, merged