feat(ui): enable students to rate tutors
litespace-org/litespace pull request #5
Opened 2024-10-15 20:44 UTC by mostafakamar2308

2024-10-16 21:10 UTC, mostafakamar2308 commented on packages/headless/src/rating.ts
> +  id,
In the custom hook itself, I am using it as a key for mutationKey

2024-10-17 08:40 UTC, neuodev commented on packages/headless/src/rating.ts
> +  id,
It is fine to remove it.

2024-10-17 08:47 UTC, neuodev requested changes

2024-10-17 08:47 UTC, neuodev commented on apps/nova/src/components/TutorProfile/DeleteRating.tsx
> +  close: () => void;
```suggestion
  close: Void;
```

2024-10-17 08:47 UTC, neuodev commented on apps/nova/src/components/TutorProfile/DeleteRating.tsx
> +  };
```suggestion
  const invalidate = useInvalidateQuery();
  const intl = useFormatMessage();
  const onSuccess = () => {
    toaster.success({ title: intl("tutor.rate.delete.success") });
    invalidate(QueryKey.TutorRatings);
    close();
  };
```

2024-10-17 08:47 UTC, neuodev commented on apps/nova/src/components/TutorProfile/DeleteRating.tsx
> +  const onSuccess = () => {
Please wrap it with `useCallback`

2024-10-17 08:47 UTC, neuodev commented on apps/nova/src/components/TutorProfile/DeleteRating.tsx
> +  const onError = (error: Error) => {
It is better to wrap it with `useCallback`

2024-10-17 08:47 UTC, neuodev commented on apps/nova/src/components/TutorProfile/DeleteRating.tsx
> +      onClick: () => deleteRating.mutate(),
```suggestion
      onClick: () => deleteRating.mutate(id),
```

2024-10-17 08:47 UTC, neuodev commented on apps/nova/src/components/TutorProfile/DeleteRating.tsx
> +  const deleteRating = useDeleteRatingTutor({ onSuccess, onError, id });
```suggestion
  const deleteRating = useDeleteRatingTutor({ onSuccess, onError });
```

2024-10-17 08:47 UTC, neuodev commented on apps/nova/src/components/TutorProfile/RateForm.tsx
> +  const invalidateRatings = useInvalidateQuery();
```suggestion
  const invalidate= useInvalidateQuery();
```

2024-10-17 08:47 UTC, neuodev commented on apps/nova/src/components/TutorProfile/Rating.tsx
> +  const showDeleteDialog = () => deleteRating.show();
```suggestion
```

2024-10-17 08:47 UTC, neuodev commented on apps/nova/src/components/TutorProfile/Rating.tsx
>    const deleteRating = useRender();
For consistency, we can rename `edit` to `editRating`
```suggestion
  const editRating = useRender();
  const deleteRating = useRender();
```

2024-10-17 08:47 UTC, neuodev commented on apps/nova/src/components/TutorProfile/Rating.tsx
> +                onClick={showEditDialog}
```suggestion
                onClick={showRating.show}
```

2024-10-17 08:47 UTC, neuodev commented on apps/nova/src/components/TutorProfile/Rating.tsx
> +                onClick={showDeleteDialog}
```suggestion
                onClick={deleteRating.show}
```

2024-10-17 08:47 UTC, neuodev commented on apps/nova/src/components/TutorProfile/Rating.tsx
> +        )}
Let's use the ternary operator syntax when conditionally render components. Not to accidentally render something unexpected. 

```suggestion
        {profile?.id === rating.rater.id ? (
          <>
            <EditRating open={edit.open} close={edit.hide} rate={rating} />

            <DeleteRating
              tutorId={rating.ratee.id}
              open={deleteRating.open}
              close={deleteRating.hide}
              id={rating.id}
            />
          </>
        ) : null}
```

2024-10-17 08:47 UTC, neuodev commented on packages/headless/src/query.ts
> +    (keys: (string | number)[]) => client.invalidateQueries({ queryKey: keys }),
Nice!

2024-10-17 14:04 UTC, mostafakamar2308 commented on packages/headless/src/rating.ts
> +  id,
Alright

2024-10-18 09:34 UTC, mostafakamar2308 commented
Change requests implemented 🚀

2024-10-18 21:37 UTC, neuodev commented
> Change requests implemented 🚀

Great! 

Please click "Re-request" review once you done with the changes and want to request another review. 

![image](https://github.com/user-attachments/assets/4ef0accf-cfbf-4174-a1b5-f0262060335e)

2024-10-18 21:46 UTC, neuodev requested changes

2024-10-18 21:46 UTC, neuodev commented on apps/nova/src/components/TutorProfile/DeleteRating.tsx
> +  }, []);
Please add empty line. 

```suggestion
  }, []);
  
```

2024-10-18 21:46 UTC, neuodev commented on apps/nova/src/components/TutorProfile/DeleteRating.tsx
> +    invalidate([QueryKeys.FindTutorRating, tutorId]);
Nice!

2024-10-18 21:46 UTC, neuodev commented on apps/nova/src/components/TutorProfile/DeleteRating.tsx
> +  }, [intl, deleteRating]);
Please add empty line

```suggestion
  }, [intl, deleteRating]);
  
```

2024-10-18 21:46 UTC, neuodev commented on apps/nova/src/components/TutorProfile/DeleteRating.tsx
> +  }, [intl, deleteRating]);
Perfect!

2024-10-18 21:46 UTC, neuodev commented on apps/nova/src/components/TutorProfile/Rating.tsx
> +      ) : null}
The problem with this approach that we render `DeleteRating` and `EditRating` for each rating component we render on the screen. 

A better approach will be to something like this:

```ts
// TutorProfile.tsx
const [editRating, setEditRating] = useState<IRate.Self | null>(null)
const [deleteRating, setDeleteRating] = useState<IRate.Self | null>(null)

return (
   <Stats query={stats} />
  <About about={tutor.data.about} />
  <ActivitiesOverview query={activity} />
  <Ratings query={ratings} setEditRating={setEditRating} setDeleteRating={setDeleteRating}  />
  {editRating && profile.id === editRating.rater.id ? <EditRating {...props}  /> : null}
  {deleteRating && profile.id === deleteRating.rater.id ? <DeleteRating {...props}  /> : null}
)
```

Using the approach mentioned above we only render one edit/delete dialog for the entire ratings list. this is more elegant, clean, performant. 

@mostafakamar2308 WDYT?

2024-10-18 22:32 UTC, mostafakamar2308 commented on apps/nova/src/components/TutorProfile/Rating.tsx
> +      ) : null}
I agree with you on that, it's certainly more clean and elegant.
I will change it today, إن شاء الله. 🚀

2024-10-19 00:12 UTC, neuodev commented
@mostafakamar2308 I merged #4, please rebase your branch on the latest master.

2024-10-20 15:06 UTC, neuodev approved these changes
Great work @mostafakamar2308! I left a minor comment. Please take a look

2024-10-20 15:06 UTC, neuodev commented on apps/nova/src/components/TutorProfile/RateForm.tsx
> +    console.log(tutor);
Left over, please delete it. 
```suggestion
```

2024-10-21 11:13 UTC, neuodev commented on apps/nova/src/components/TutorProfile/RateForm.tsx
> +  const invalidateRatings = useInvalidateQuery();
```suggestion
  const invalidate = useInvalidateQuery();
```

2024-10-21 11:14 UTC, neuodev commented on apps/nova/src/components/TutorProfile/Rating.tsx
> +}> = ({ rating, handleEdit, handleDelete }) => {
```suggestion
  onEdit: (rating: IRating.Populated) => void;
  onDelete: (payload: {
    ratingId: number;
    tutorId: number;
  }) => void;
}> = ({ rating, handleEdit, handleDelete }) => {
```

2024-10-21 11:15 UTC, neuodev commented on apps/nova/src/components/TutorProfile/Ratings.tsx
> +  const [ratingDeleted, setRatingDeleted] = useState<{
```suggestion
  const [editRating, setEditRating] = useState<IRating.Populated | null>(
    null
  );
  const [deleteRating, setDeleteRating] = useState<{
```

2024-10-21 11:16 UTC, neuodev commented on apps/nova/src/components/TutorProfile/Ratings.tsx
> +  const deleteRating = useRender();
We no longer need `useRender`  as we can check if `editRating` or `deleteRating` is not `null`

```suggestion
```

2024-10-21 11:17 UTC, neuodev commented on apps/nova/src/components/TutorProfile/Ratings.tsx
> +  }, []);
```suggestion
  const onEditRating = useCallback((rating: IRating.Populated) => setEditRating(rating), []);
```

2024-10-21 11:18 UTC, neuodev commented on apps/nova/src/components/TutorProfile/Ratings.tsx
> +  );
```suggestion
  const onDeleteRating = useCallback(
    (payload: { ratingId: number; tutorId: number }) => setRatingDeleted(payload),
    []
  );
```

2024-10-21 11:19 UTC, neuodev commented on apps/nova/src/components/TutorProfile/Ratings.tsx
> +  }, []);
```suggestion
  const onClose = useCallback(() => 
    setEditRating(null);
    setDeleteRating(null);
  }, []);  
```

2024-10-21 11:20 UTC, neuodev commented on apps/nova/src/components/TutorProfile/Ratings.tsx
> +  });
It is better to initialize it to null. 

```suggestion
    ratingId: number;
    tutorId: number;
  } | null>(null);
```

2024-10-21 11:21 UTC, neuodev commented on apps/nova/src/components/TutorProfile/Ratings.tsx
> +      ) : null}
```suggestion
      {editRating ? (
        <EditRating
          open
          close={onClose}
          rate={editRating}
        />
      ) : null}
      
      {deleteRating ? (
        <DeleteRating
          open
          tutorId={deleteRating.tutorId}
          close={onClose}
          id={deleteRating.ratingId}
        />
      ) : null}
```

2024-10-21 15:06 UTC, neuodev approved these changes

2024-10-21 15:07 UTC, merged