Mo(dashboard): render users
litespace-org/litespace pull request #6
Opened 2024-10-16 16:51 UTC by moalidv

2024-10-16 17:07 UTC, moalidv commented
I pushed this branch from my local on (mo/dashboard-users) which was branched originally from master 
I don't know why all these files and changes appear here in this PR.

2024-10-18 21:31 UTC, neuodev requested changes
Great work @moalidv! Please take a look at my minor comments above! Thanks in advance!

2024-10-18 21:31 UTC, neuodev commented on apps/dashboard/src/components/Users/List.tsx
> +        },
```suggestion
        cell: (info) => <BooleanField checked={info.row.original.password} />
```

2024-10-18 21:31 UTC, neuodev commented on apps/dashboard/src/components/Users/List.tsx
> +  if (!query.data) return null;
@moalidv please add the error element

2024-10-18 21:31 UTC, neuodev commented on apps/dashboard/src/pages/Root.tsx
> +  const navigate = useNavigate();
Please add empty line. 
```suggestion
  const navigate = useNavigate();
  
```

2024-10-18 21:31 UTC, neuodev commented on apps/dashboard/src/pages/Users.tsx
> +        </div> */}
Left over.

```suggestion
```

2024-10-18 21:31 UTC, neuodev commented on packages/luna/src/locales/ar-eg.json
> +  "dashboard.user.fullMonthPrice": "السعر الشهري",
There is no such thing as `fullMonthPrice` for the user. 
```suggestion
```

2024-10-18 21:49 UTC, neuodev approved these changes

2024-10-18 21:50 UTC, merged