feat(nova): Added redirect to feedback page after call end
litespace-org/litespace pull request #9
Opened 2024-10-17 22:26 UTC by mostafakamar2308

2024-10-17 23:01 UTC, neuodev requested changes

2024-10-17 23:01 UTC, neuodev commented on apps/nova/src/pages/Callfeedback.tsx
> +      <Link to={"/"}>
```suggestion
      <Link to={Route.Home}>
```

2024-10-17 23:01 UTC, neuodev commented on apps/nova/src/pages/Call.tsx
> +    id && navigate(Route.CallFeedback.replace(":id", id));
```suggestion
   if (id) navigate(Route.CallFeedback.replace(":id", id));
```

2024-10-17 23:01 UTC, neuodev commented on apps/nova/src/pages/Call.tsx
> +    // TODO: This didn't stop the camera and needs further investigations
Nice 🚀 !!

2024-10-18 09:35 UTC, mostafakamar2308 commented
Change requests implemented 🚀

2024-10-18 21:52 UTC, neuodev commented
> Change requests implemented 🚀

Thank you! 

Please click "Re-request review" once you are done with your changes. 

![image](https://github.com/user-attachments/assets/912310c7-cbd5-4f3e-9f56-fef292b25f1c)

2024-10-18 21:52 UTC, neuodev approved these changes

2024-10-20 09:59 UTC, mostafakamar2308 commented
@neuodev  
Do we need to migrate this to master directly? As I see, It's not related to migrate-queries.

2024-10-20 15:25 UTC, neuodev commented
Another solution, is to rebase you work on top of the latest master and drop unrelated commits.

2024-10-20 15:26 UTC, neuodev commented
One last comment is the commit/PR title should start by lowercase. 

```diff
- feat(nova): Added redirect to feedback page after call end
+ feat(nova): added redirect to feedback page after call end
```

2024-10-21 11:28 UTC, neuodev commented
> One last comment is the commit/PR title should start by lowercase.
> 
> ```diff
> - feat(nova): Added redirect to feedback page after call end
> + feat(nova): added redirect to feedback page after call end
> ```

@mostafakamar2308 please update the PR title and the commit message.

2024-10-21 11:28 UTC, neuodev approved these changes

2024-10-21 11:29 UTC, neuodev commented
@mostafakamar2308 please rebase this branch on top of `master` as I cannot find a reason why it is based on `mk/migrate-queries`

2024-10-21 15:09 UTC, neuodev commented
Please rebase you merge request and resolve the conflicts @mostafakamar2308!

2024-10-21 15:56 UTC, closed without merging